# Generated by Django 5.0.4 on 2024-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.DateTimeField(max_length=255, unique=True, verbose_name='ID кошелька'),
        ),
    ]
