# Generated by Django 5.0.4 on 2024-05-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.DateTimeField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID кошелька'),
        ),
    ]
