# Generated by Django 5.0.4 on 2024-05-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_comleted', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sent', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_received', to=settings.AUTH_USER_MODEL, verbose_name='К пользователю')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
